[package]
name = "cntr-fuse"
version = "0.3.2-pre1"
authors = ["Mic92"]
build = "build.rs"
description = "Rust library for filesystems in userspace (FUSE) (fork with functionality needed for the cntr project)"
homepage = "https://github.com/Mic92/cntr-fuse"
repository = "https://github.com/Mic92/cntr-fuse"
readme = "README.md"
keywords = ["fuse", "filesystem", "system", "bindings"]
categories = ["api-bindings", "filesystem"]
license = "MIT"

[build-dependencies]
pkg-config = "0.3"

[dependencies]
libc = "0.2"
log = "0.3"
time = "0.1"
thread-scoped = "1"

[dev-dependencies]
env_logger = "0.3"

[lib]
name = "fuse"
path = "src/lib.rs"

[features]
libfuse = []
